plugins {
    id 'java'
    id 'groovy'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.spockframework:spock-core:2.4-M7-groovy-4.0'
    testImplementation 'org.apache.groovy:groovy:4.0.29'
}

testing {
    suites {
        test {
            useJUnitJupiter('6.0.1')
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
